### ISSUE TITLE
Wheels for 3.7?

### ISSUE THREAD

**Issue by ngoldbaum** [MacPython/h5py-wheels#7]
It would be nice to get wheels for 3.7, particularly for mac so I can run CI against 3.7 without needing to install hdf5 on the CI builder.

**Comment by ngoldbaum** [comment]
see https://github.com/MacPython/h5py-wheels/pull/8

**Comment by matthew-brett** [comment]
Uploaded.  What's the plan for the Windows wheels?

**Comment by ngoldbaum** [comment]
It looks like they're already up there?

**Comment by matthew-brett** [comment]
Ah - so they are - good job.
