### ISSUE TITLE
h5py-2.8.0-cp27-cp27m-manylinux1_x86_64.whl missing from PyPI

### ISSUE THREAD

**Issue by ryanvolz** [MacPython/h5py-wheels#9]
Not sure if this is the right place to report this, but I noticed in the course of making wheels for my own package that the h5py-2.8.0-cp27-cp27m-manylinux1_x86_64.whl wheel present on http://wheels.scipy.org/ is missing from PyPI. My package attempts to install h5py as a dependency for testing with that version/platform/unicode combination, falls back to the source package because the wheel is missing, and subsequently fails to build h5py.

I assume this one just slipped through the cracks and needs to be uploaded by someone with the authority to do so. Thanks!

**Comment by matthew-brett** [comment]
Oops - I uploaded it now.  Sorry, those narrow-unicode ones don't get used very much.

**Comment by ryanvolz** [comment]
Ha, clearly. It only came up for me thanks to multibuild, so thanks for that!
